"""
AI-generated text detector.

Uses a fine-tuned RoBERTa model to distinguish human-written text from
text generated by large language models (GPT-4, Claude, Gemini, Llama, etc.).
Also performs heuristic analysis (perplexity, burstiness, entropy).
"""
import asyncio
import logging
import math
import re
from typing import Any, Dict, List

logger = logging.getLogger(__name__)

_AI_GENERATORS = {
    "very_low_perplexity": "GPT-4 / Claude / Gemini",
    "low_burstiness": "ChatGPT / Bard",
    "high_uniformity": "GPT-3.5 / Llama 2",
    "repetitive_phrasing": "low-temperature LLM output",
}


class TextDetector:
    """Detect AI-generated text using transformer classification + heuristics."""

    def __init__(self):
        self._tokenizer = None
        self._model = None
        self._device = None

    async def load(self):
        loop = asyncio.get_event_loop()
        await loop.run_in_executor(None, self._load_sync)

    def _load_sync(self):
        import torch
        from transformers import AutoTokenizer, AutoModelForSequenceClassification

        self._device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        logger.info("TextDetector using device: %s", self._device)

        # roberta-base-openai-detector classifies real vs AI-generated text
        model_name = "roberta-base-openai-detector"
        self._tokenizer = AutoTokenizer.from_pretrained(
            model_name,
            cache_dir="/tmp/models",
        )
        self._model = AutoModelForSequenceClassification.from_pretrained(
            model_name,
            cache_dir="/tmp/models",
        ).to(self._device)
        self._model.eval()

    async def analyze(self, text: str) -> Dict[str, Any]:
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(None, self._analyze_sync, text)

    def _analyze_sync(self, text: str) -> Dict[str, Any]:
        import torch

        if not text or not text.strip():
            return self._empty_result()

        try:
            inputs = self._tokenizer(
                text,
                return_tensors="pt",
                truncation=True,
                max_length=512,
                padding=True,
            ).to(self._device)

            with torch.no_grad():
                outputs = self._model(**inputs)
                probs = torch.softmax(outputs.logits, dim=-1)
                # Label 0 = Real, Label 1 = Fake/AI-generated
                ai_confidence = float(probs[0][1].item())
        except Exception as exc:
            logger.error("TextDetector model inference failed: %s", exc)
            ai_confidence = 0.0

        heuristic_artifacts = self._detect_heuristic_artifacts(text)
        model_guess = self._guess_generator(ai_confidence, heuristic_artifacts)

        # Blend model confidence with heuristic signals
        heuristic_boost = len(heuristic_artifacts) * 0.05
        final_confidence = min(1.0, ai_confidence + heuristic_boost)

        return {
            "is_ai_generated": final_confidence > 0.5,
            "confidence": round(final_confidence, 4),
            "ai_artifacts": heuristic_artifacts,
            "generator_model_guess": model_guess,
            "word_count": len(text.split()),
            "sentence_count": len(re.split(r"[.!?]+", text.strip())),
        }

    def _detect_heuristic_artifacts(self, text: str) -> List[str]:
        """Lightweight heuristic checks for LLM-generated text patterns."""
        artifacts = []
        words = text.split()
        if not words:
            return artifacts

        # 1. Burstiness: human text has variable sentence length; LLMs are uniform
        sentences = [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]
        if len(sentences) >= 4:
            lengths = [len(s.split()) for s in sentences]
            mean_len = sum(lengths) / len(lengths)
            variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
            burstiness = math.sqrt(variance) / (mean_len + 1e-9)
            if burstiness < 0.25:
                artifacts.append("low_burstiness")

        # 2. Perplexity proxy: flag suspiciously uniform character-level entropy
        char_freq: Dict[str, int] = {}
        for ch in text.lower():
            char_freq[ch] = char_freq.get(ch, 0) + 1
        total = sum(char_freq.values())
        entropy = -sum((c / total) * math.log2(c / total) for c in char_freq.values() if c > 0)
        if entropy < 3.8:  # unusually low entropy
            artifacts.append("very_low_perplexity")

        # 3. High lexical uniformity (type-token ratio)
        unique_words = set(w.lower().strip(".,!?;:") for w in words)
        ttr = len(unique_words) / max(len(words), 1)
        if ttr < 0.45 and len(words) > 50:
            artifacts.append("high_uniformity")

        # 4. Repetitive transitional phrases common in LLM output
        llm_phrases = [
            "furthermore", "moreover", "in conclusion", "it is important to note",
            "it's worth noting", "in summary", "to summarize", "as mentioned",
            "it is crucial", "this highlights", "plays a crucial role",
        ]
        text_lower = text.lower()
        phrase_hits = sum(1 for p in llm_phrases if p in text_lower)
        if phrase_hits >= 3:
            artifacts.append("repetitive_phrasing")

        return artifacts

    def _guess_generator(self, confidence: float, artifacts: List[str]) -> str:
        if confidence < 0.3:
            return "human-written"
        for artifact in artifacts:
            if artifact in _AI_GENERATORS:
                return _AI_GENERATORS[artifact]
        if confidence > 0.8:
            return "GPT-4 / Claude / Gemini"
        return "unknown LLM"

    def _empty_result(self):
        return {
            "is_ai_generated": False,
            "confidence": 0.0,
            "ai_artifacts": [],
            "generator_model_guess": "unknown",
            "word_count": 0,
            "sentence_count": 0,
        }
